.PHONY: new-0-original
new-0-original:
# https://vuepress.vuejs.org/guide/getting-started.html
	mkdir 0-original
	cd 0-original && npm install --save-dev vuepress

.PHONY: new-1-awesome
new-1-awesome:
	cp -r 0-original 1-awesome
	cd 1-awesome && mkdir data